### ISSUE TITLE
config.py not creating

### ISSUE THREAD

**Issue by KN4KNG** [n8acl/aprsnotify#1]
Should edit line #9 in setup.py

from:
config_fname = "test"

to:
config_fname = "config"

**Comment by n8acl** [comment]
Good Catch. Sorry about that. It's been fixed. Should be able to use it now.

**Comment by KN4KNG** [comment]
Right on! I'm trying this out now so I'll update with anything else I see. Great work by the way!

**Comment by n8acl** [comment]
Thanks much! I appreciate it...
