### ISSUE TITLE
New VM Install - error around idna and doesn't appear to run flask at the end

### ISSUE THREAD

**Issue by Russell-KV4S** [n8acl/aprsnotify#6]
Attempting to install on:

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=Debian

output window:

`root@kv4s:/home/kv4s/aprsnotify# pip3 install -r requirements.txt
Collecting python-telegram-bot (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/75/30/6e63bd6686d83cfd0e2f22f05cfc411571cf7934d72b62636e4bee0dd91f/python_telegram_bot-20.0-py3-none-any.whl (484kB)
    100% |████████████████████████████████| 491kB 2.2MB/s
Collecting Tweepy (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/ad/62/35e988300d82513fb5e1168108d879a5462072ce1d5137816f91a674df7e/tweepy-4.12.1-py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 4.8MB/s
Collecting geopy (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/e4/00/6313c0ffdd230164890f433019749189e0b884562bdc170e9c3a3454b3a6/geopy-2.3.0-py3-none-any.whl (119kB)
    100% |████████████████████████████████| 122kB 5.8MB/s
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (2.21.0)
Collecting aprslib (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/d7/b4/4b82e41dc007cfa68ee076ef905b823f841e4ce868fe7ee8b22cfe26796a/aprslib-0.7.2-py2.py3-none-any.whl (44kB)
    100% |████████████████████████████████| 51kB 7.9MB/s
Collecting mastodon.py (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/08/9b/1e3a058da4ce91bb1ebe4a025d56e9cd774461f924ea2a87c2049ad2ac98/Mastodon.py-1.8.0-py2.py3-none-any.whl (64kB)
    100% |████████████████████████████████| 71kB 6.9MB/s
Collecting discord_webhook (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/3b/85/ad722bb6083ba67bdf1fae93a244ea574eead8be147aaed9503984d62d5e/discord_webhook-0.17.0-py3-none-any.whl
Collecting matterhook (from -r requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/7a/07/c69624a4e1cc08ca0bb61da314c25ed0d39c1be3bbf452a810ae20d9d538/matterhook-0.2.tar.gz
Collecting httpx~=0.23.1 (from python-telegram-bot->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/ac/a2/0260c0f5d73bdf06e8d3fc1013a82b9f0633dc21750c9e3f3cb1dba7bb8c/httpx-0.23.3-py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 4.0MB/s
Collecting oauthlib<4,>=3.2.0 (from Tweepy->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/7e/80/cab10959dc1faead58dc8384a781dfbf93cb4d33d50988f7a69f1b7c9bbe/oauthlib-3.2.2-py3-none-any.whl (151kB)
    100% |████████████████████████████████| 153kB 4.9MB/s
Collecting requests-oauthlib<2,>=1.2.0 (from Tweepy->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/6f/bb/5deac77a9af870143c684ab46a7934038a53eb4aa975bc0687ed6ca2c610/requests_oauthlib-1.3.1-py2.py3-none-any.whl
Collecting geographiclib<3,>=1.52 (from geopy->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/9f/5a/a26132406f1f40cf51ea349a5f11b0a46cec02a2031ff82e391c2537247a/geographiclib-2.0-py3-none-any.whl (40kB)
    100% |████████████████████████████████| 40kB 6.6MB/s
Collecting blurhash>=1.1.4 (from mastodon.py->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/80/08/163cb166a2464223a5eb8890a92cc1cf7e8c7c79a2c75e497e3d8f3a4711/blurhash-1.1.4-py2.py3-none-any.whl
Collecting python-dateutil (from mastodon.py->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl (247kB)
    100% |████████████████████████████████| 256kB 2.8MB/s
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from mastodon.py->-r requirements.txt (line 6)) (1.12.0)
Collecting decorator>=4.0.0 (from mastodon.py->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/d5/50/83c593b07763e1161326b3b8c6686f0f4b0f24d5526546bee538c89837d6/decorator-5.1.1-py3-none-any.whl
Collecting python-magic (from mastodon.py->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/6c/73/9f872cb81fc5c3bb48f7227872c28975f998f3e7c2b1c16e95e6432bbb90/python_magic-0.4.27-py2.py3-none-any.whl
Collecting rfc3986[idna2008]<2,>=1.3 (from httpx~=0.23.1->python-telegram-bot->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/c4/e5/63ca2c4edf4e00657584608bee1001302bbf8c5f569340b78304f2f446cb/rfc3986-1.5.0-py2.py3-none-any.whl
Collecting httpcore<0.17.0,>=0.15.0 (from httpx~=0.23.1->python-telegram-bot->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/04/7e/ef97af4623024e8159993b3114ce208de4f677098ae058ec5882a1bf7605/httpcore-0.16.3-py3-none-any.whl (69kB)
    100% |████████████████████████████████| 71kB 6.5MB/s
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from httpx~=0.23.1->python-telegram-bot->-r requirements.txt (line 1)) (2018.8.24)
Collecting sniffio (from httpx~=0.23.1->python-telegram-bot->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/c3/a0/5dba8ed157b0136607c7f2151db695885606968d1fae123dc3391e0cfdbf/sniffio-1.3.0-py3-none-any.whl
Requirement already satisfied: idna; extra == "idna2008" in /usr/lib/python3/dist-packages (from rfc3986[idna2008]<2,>=1.3->httpx~=0.23.1->python-telegram-bot->-r requirements.txt (line 1)) (2.6)
Collecting anyio<5.0,>=3.0 (from httpcore<0.17.0,>=0.15.0->httpx~=0.23.1->python-telegram-bot->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/77/2b/b4c0b7a3f3d61adb1a1e0b78f90a94e2b6162a043880704b7437ef297cad/anyio-3.6.2-py3-none-any.whl (80kB)
    100% |████████████████████████████████| 81kB 5.6MB/s
Collecting h11<0.15,>=0.13 (from httpcore<0.17.0,>=0.15.0->httpx~=0.23.1->python-telegram-bot->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/95/04/ff642e65ad6b90db43e668d70ffb6736436c7ce41fcc549f4e9472234127/h11-0.14.0-py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 6.6MB/s
Collecting typing-extensions; python_version < "3.8" (from anyio<5.0,>=3.0->httpcore<0.17.0,>=0.15.0->httpx~=0.23.1->python-telegram-bot->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/0b/8e/f1a0a5a76cfef77e1eb6004cb49e5f8d72634da638420b9ea492ce8305e8/typing_extensions-4.4.0-py3-none-any.whl
Building wheels for collected packages: matterhook
  Running setup.py bdist_wheel for matterhook ... done
  Stored in directory: /root/.cache/pip/wheels/f0/66/f0/ab0d427b2d303a96079fe403e00adb96e27128bbc7a6379ae7
Successfully built matterhook
anyio 3.6.2 has requirement idna>=2.8, but you'll have idna 2.6 which is incompatible.
tweepy 4.12.1 has requirement requests<3,>=2.27.0, but you'll have requests 2.21.0 which is incompatible.
Installing collected packages: rfc3986, sniffio, typing-extensions, anyio, h11, httpcore, httpx, python-telegram-bot, oauthlib, requests-oauthlib, Tweepy, geographiclib, geopy, aprslib, blurhash, python-dateutil, decorator, python-magic, mastodon.py, discord-webhook, matterhook
Successfully installed Tweepy-4.12.1 anyio-3.6.2 aprslib-0.7.2 blurhash-1.1.4 decorator-5.1.1 discord-webhook-0.17.0 geographiclib-2.0 geopy-2.3.0 h11-0.14.0 httpcore-0.16.3 httpx-0.23.3 mastodon.py-1.8.0 matterhook-0.2 oauthlib-3.2.2 python-dateutil-2.8.2 python-magic-0.4.27 python-telegram-bot-20.0 requests-oauthlib-1.3.1 rfc3986-1.5.0 sniffio-1.3.0 typing-extensions-4.4.0
root@kv4s:/home/kv4s/aprsnotify# python3 an_util.py
Traceback (most recent call last):
  File "an_util.py", line 2, in <module>
    from flask import Flask, render_template, request, Markup
ModuleNotFoundError: No module named 'flask'`

**Comment by n8acl** [comment]
Just ting loose ends. Apparently I deleted the required flask package from the requirements.txt file. Added it back and repushed. Closing this Issue as resolved. Thanks for letting me know about the issue! I didn't realize I had done it.

**Comment by DK2BN** [comment]
Flask Package is still missing in requirements.txt file, had to install it manually.
